[package]
name = "reflines"
version = "0.0.1"
authors = ["Markus Ineichen <kusi.ineichen@gmail.com>"]
edition = "2018"

[[bench]]
name = "bufread_lines"
harness = false

[dependencies]
thiserror = "1.0"
linereader = "0.4"

[dev-dependencies]
criterion = "0.3"